name: Foodgram CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Причина ручного запуска деплоя'
        required: false
        default: 'Manual deployment triggered'

jobs:
  build_backend:
    name: Build and publish backend image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4
        
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest
          cache-to: type=inline

  build_frontend:
    name: Build and publish frontend image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4
        
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest
          cache-to: type=inline

  build_nginx:
    name: Build and publish Nginx proxy image
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4
        
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./infra/
          file: ./infra/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_gateway:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/foodgram_gateway:latest
          cache-to: type=inline
